language: node_js
addons:
  ssh_known_hosts: insitehubtest.com
node_js:
- stable
install:
- npm install
before_script:
- npm run build
after_success: npm run coverage
script:
- nohup npm run start
before_install:
- openssl aes-256-cbc -K $encrypted_dee9d8843364_key -iv $encrypted_dee9d8843364_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
- ssh -i ./deploy_rsa ubuntu@insitehubtest.com pwd
